name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode Keystore from Base64 and save it to a file
      env:
        ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
      run: |
          tmp_keystore_directory="${RUNNER_TEMP}"/keystore
          mkdir "${tmp_keystore_directory}"
          echo $ENCODED_KEYSTORE | base64 -d > "${tmp_keystore_directory}"/keystore.jks
          echo "SIGNING_KEYSTORE_FILE_PATH="${tmp_keystore_directory}"/keystore.jks" >> $GITHUB_ENV           

    - name: Build Release apk
      env:
        SIGNING_KEY_STORE_PATH: ${{ env.SIGNING_KEYSTORE_FILE_PATH }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleDevelopmentRelease

    - name: Create Service Credential File
      env:
        SERVICE_CREDENTIAL_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $SERVICE_CREDENTIAL_STRING > firebase-app-distribution.json
          
    - name: Upload aab to Firebase App Distribution
      env:
        GOOGLE_SERVICES_JSON: "firebase-app-distribution.json"
        FIREBASE_APP_ID: "${{ secrets.FIREBASE_APP_ID }}"  
      run: ./gradlew appDistributionUploadDevelopmentRelease
