name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    environment: qa-debug

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
      run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

    - name: Build Release apk
      env:
        SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Create Service Credential File
      env:
        SERVICE_CREDENTIAL_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $SERVICE_CREDENTIAL_STRING > firebase-app-distribution.json
          
    - name: Upload aab to Firebase App Distribution
      env:
        GOOGLE_SERVICES_JSON: "firebase-app-distribution.json"
        FIREBASE_APP_ID: "${{ secrets.FIREBASE_APP_ID }}"  
      run: ./gradlew appDistributionUploadRelease
