name: Build development on a DL server and upload to GitHub artifacts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Must match the version specified in the "compileOptions" block in the Gradle file.
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode Keystore from Base64 and save it to a file
      env:
        ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
      run: |
          tmp_keystore_directory="${RUNNER_TEMP}"/keystore
          mkdir "${tmp_keystore_directory}"
          echo $ENCODED_KEYSTORE | base64 -d > "${tmp_keystore_directory}"/keystore.jks
          echo "SIGNING_KEYSTORE_FILE_PATH="${tmp_keystore_directory}"/keystore.jks" >> $GITHUB_ENV           

    - name: Build Release apk
      env:
        API_BASE_URL: ${{ vars.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        SIGNING_KEY_STORE_PATH: ${{ env.SIGNING_KEYSTORE_FILE_PATH }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleDevelopmentRelease

    - name: Upload Release Build to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: app/build/outputs/apk/development/release/
