name: Build QA Debug and send to Firebase

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: qa-debug

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleQa
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.GOOGLE_SERVICES_JSON }}
        file: app/build/outputs/apk/qa/app-qa.apk
