name: Build QA Debug and send to Firebase

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: qa

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleQa
    - name: upload artifact to Firebase App Distribution
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        firebaseServiceAccount: "${{ secrets.GOOGLE_SERVICES_JSON }}" 
        projectId: "${{ secrets.FIREBASE_APP_ID }}" 
        file: app/build/outputs/apk/qa/app-qa.apk
